### ISSUE TITLE
TypeError: Value cannot be an array for the operator "IN"

### ISSUE THREAD

**Issue by BeardedBry** [d34dman/drupal-jsonapi-params#12]
I'm getting this error.
TypeError: Value cannot be an array for the operator "IN"

Here is my parameter:
`apiParams.addFilter('field_businesses.drupal_internal__tid',['293','2250'],'IN');`

Thanks for any help.

**Comment by d34dman** [comment]
![DefaultValues test ts — drupal-jsonapi-params 2020-09-21 10-09-22](https://user-images.githubusercontent.com/1006481/93744693-8cbbd980-fbf2-11ea-9065-e1f1a4109b47.png)

@BeardedBry thanks for the bug report, just wrote a test to confirm the error. So fix shouldn't be far away.
