### ISSUE TITLE
Allow extra query string params to be added.

### ISSUE THREAD

**Issue by patrickcate** [d34dman/drupal-jsonapi-params#23]
It would be great if there was a method that allowed for extra arbitrary query strings to be added to the query. The https://www.drupal.org/project/jsonapi_include module requires `jsonapi_include=1` be added to the url for instance.

Something like:

```js
apiParams
  // Add Extra query string.
  .addExtra('jsonapi_include', 1)
```

would easily enable support for this.

**Comment by d34dman** [comment]
Thanks for the suggestion @patrickcate ,
we now have `addCustomParam` method in release 1.2.0.
```js
apiParams
  // To add `foo=bar` to the query.
  .addCustomParam({foo: 'bar'})
  // To add `foo[bar]=baz` to the query.
  .addCustomParam({ foo: {bar: 'baz'}})
  // To add `bar[0]=a&bar[1]=b&bar[2]=c` to the query.
  .addCustomParam({ bar: ['a', 'b', 'c']})
```
