### ISSUE TITLE
Issue with NULL based operators.

### ISSUE THREAD

**Issue by Decipher** [d34dman/drupal-jsonapi-params#7]
As a developer I want to apply an IS NULL operator without a filter value.

While I'm not familiar with Typescript, it appears the `FilterItem` type requires the value property, but a NULL based operator appears not to work with a value set.

**Comment by d34dman** [comment]
@Decipher I guess i understand what you are trying to do, but could you please provide an example test scenario? That is, a minimal javascript code, and expected output :)

**Comment by d34dman** [comment]
NOTE TO SELF: This would also need to be applied for `IS NOT NULL`

**Comment by d34dman** [comment]
Ah! looks like we must also include proper support for `BETWEEN` and `NOT BETWEEN`, which should be accepting two parameters.

**Comment by Decipher** [comment]
@d34dman https://github.com/Realityloop/druxt-blocks/blob/develop/src/components/DruxtBlockRegion.vue#L79

P.s., Am active on Drupal Slack #contenta atm.

**Comment by Decipher** [comment]
Active demo: https://8juco.sse.codesandbox.io/
